---
application:
  name: "google-drive-telegram-bot"
  project: "google-drive-telegram"
  organization: "QoveryCommunity"
routers:
- name: "main-google-drive-telegram"
  routes:
  - application_name: "google-drive-telegram-bot"
    paths:
    - "/*"
